import { beforeAll, describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { loadEntries, loadLogs, STAGED_PREFIX } from '../src/server/content-fs';

/**
 * The filesystem loader is the Next build's only route to the content, and the one failure that
 * would be invisible is **a silently smaller site**: an entry that stops validating, or a folder
 * the glob stops matching, does not produce a broken page — it produces no page, no error, and a
 * portfolio quietly missing a piece of work. Astro had the same exposure and answered it by
 * failing the build; these are the equivalents.
 *
 * Page-level parity against the Astro output is a separate question, answered by the harness fleet
 * once the pages exist. This is the layer under that.
 */

/**
 * Stage the images before asking whether they are staged.
 *
 * **This test was green on every developer machine and red on every CI run for five commits**, and
 * the reason is worth writing down because it is the most ordinary way a test stops meaning
 * anything. `public/content/` is generated by `scripts/stage-content-images.mjs` and is gitignored
 * — correctly, the originals in `src/content/` are the only copies under version control. The
 * script runs as the first step of `npm run dev` and `npm run build`. So on a machine where anyone
 * has ever built, the directory exists and the check below passes; on a fresh checkout it does not,
 * and CI runs `npm test` *before* `npm run build`.
 *
 * The check was therefore passing locally for a reason that had nothing to do with what it claims
 * to verify: not "the loader's references resolve to staged files" but "somebody built here
 * recently". Adding `stage:images` to the workflow would have made CI green and left that intact.
 *
 * Running the script here fixes both. The test now owns its precondition, works on a clean clone,
 * and — because it stages and *then* checks — actually tests the thing its docstring claims: that
 * the script's destination shape and `content-fs.ts`'s rewritten reference still agree. Those are
 * two pieces of code that have to match and no compiler relates them.
 *
 * Spawned rather than imported. The script is a top-level-await module with no exports that does
 * its work as an import side effect; `await import(…)` would run it once and then be silently
 * cached, which is a subtlety nobody should have to know to read this file. It takes about 0.7s.
 */
beforeAll(() => {
  execFileSync(process.execPath, ['scripts/stage-content-images.mjs'], {
    cwd: process.cwd(),
    stdio: 'pipe',
  });
});

const CONTENT = path.join(process.cwd(), 'src', 'content');
const onDisk = (c: string) =>
  readdirSync(path.join(CONTENT, c), { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
    .map((d) => d.name)
    .sort();

describe('the filesystem loader sees the whole site', () => {
  it('loads every entry folder on disk, and no others', async () => {
    const loaded = (await loadEntries()).map((e) => e.id).sort();
    expect(loaded).toEqual(onDisk('entries'));
  });

  it('loads every log folder on disk, and no others', async () => {
    const loaded = (await loadLogs()).map((e) => e.id).sort();
    expect(loaded).toEqual(onDisk('logs'));
  });

  /**
   * The id *is* the URL. `content.config.ts` derives it by stripping `/index.md`, so a loader that
   * derived it any other way would move every entry's address without anything failing — the pages
   * would build, at different URLs, and every existing link would break at once.
   */
  it('gives each item the id Astro gives it — the folder name, and nothing else', async () => {
    for (const e of await loadEntries()) {
      expect(e.id, e.filePath).not.toContain('/');
      expect(e.filePath.endsWith(path.join(e.id, 'index.md'))).toBe(true);
    }
  });

  /**
   * Astro resolved covers itself and failed the build on a missing one. Here the file is staged by
   * a separate script, so the reference and the file are produced by two different pieces of code
   * — which is exactly the arrangement where they drift apart. Checked, not assumed.
   */
  it('resolves every cover to a file that has actually been staged', async () => {
    for (const e of await loadEntries()) {
      expect(e.data.cover.src.startsWith(`${STAGED_PREFIX}/entries/${e.id}/`), e.id).toBe(true);
      const onPublic = path.join(process.cwd(), 'public', e.data.cover.src.replace(/^\//, ''));
      /* The old message here said "run scripts/stage-content-images.mjs", which was true when the
         test depended on somebody having done that and is misleading now that it does it itself:
         if this fails, staging *has* run and did not produce the file, so the fault is in the
         script's traversal or in the reference `content-fs.ts` built — which is the drift this
         check exists to catch, and pointing at the wrong remedy would send the reader past it. */
      expect(
        existsSync(onPublic),
        `${e.id}: staging ran but produced no ${onPublic.replace(process.cwd() + path.sep, '')} — the loader's reference and the staging script disagree`,
      ).toBe(true);
    }
  });

  /**
   * A cover with no dimensions is a page that reflows as it loads. Every cover on this site is a
   * generated SVG, so this is really a check on the viewBox reader in `measure()` — sharp would
   * otherwise hand back a density-derived guess, and a wrong ratio is not visible in any diff.
   */
  it('measures every cover, and never reports a zero', async () => {
    for (const e of await loadEntries()) {
      expect(e.data.cover.width, e.id).toBeGreaterThan(0);
      expect(e.data.cover.height, e.id).toBeGreaterThan(0);
    }
  });

  /**
   * The loader returns drafts and leaves the filtering to its callers, the same contract Astro's
   * `getCollection` has. Asserted rather than left implicit, because the *other* reading — a
   * loader that drops drafts itself — is equally reasonable, and the day someone assumes it is the
   * day a draft ships.
   */
  it('returns drafts too, leaving the decision to the caller', async () => {
    const drafts = (await loadEntries()).filter((e) => e.data.draft);
    expect(drafts.length).toBeGreaterThan(0);
  });

  /**
   * `body` is raw markdown, exactly as Astro's is. If it ever arrives rendered, the comment-
   * stripping step would be operating on HTML instead of markdown and the provenance notes several
   * entries carry would reach the page.
   */
  it('hands back raw markdown, not rendered HTML', async () => {
    for (const e of await loadEntries()) {
      expect(e.body, e.id).not.toContain('<p>');
    }
  });
});
