/**
 * Writes src/styles/tokens.css from src/design/tokens.mjs — the only way that file is made.
 *
 *   node scripts/build-tokens.mjs           write it
 *   node scripts/build-tokens.mjs --check   exit 1 if it is stale (tests/design-tokens.test.ts does this too)
 *
 * The output is ordinary CSS for Tailwind v4: an `@theme static` block (so the primitives and the
 * semantic colours become utilities like `bg-surface`, and every variable is emitted whether or not a
 * utility uses it — the semantics point at primitives through var()), then the non-utility scales on
 * :root, the dark theme's pointers on `.dark`, and the print palette.
 *
 * **Colours are written as sRGB hex, with their OKLCH beside them.** OKLCH is the space they are
 * designed in; sRGB is the space every one of them is inside (the token test enforces it), so the hex
 * is the same colour to the last bit a screen can show. And a computed `oklch()` reaches script as
 * `oklch(…)`, which the fleet's contrast checks (arena.mjs) read as three numbers of sRGB — a hex
 * token computes to `rgb()`, which every reader of the page understands. Mixes are `in srgb` for the
 * same reason.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as T from '../src/design/tokens.mjs';
import { css, oklchToHex } from '../src/design/color.mjs';

const OUT = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url));

const ref = (r) => (r === 'void' ? 'var(--color-void)' : `var(--color-${r.replace('.', '-')})`);

function shadow(layers) {
  return layers
    .map(
      ([x, y, blur, spread, a]) =>
        `${x} ${y}px ${blur}px ${spread}px color-mix(in srgb, var(--color-shadow) min(100%, calc(${Math.round(a * 100)}% * var(--shadow-k))), transparent)`,
    )
    .join(', ');
}

export function render() {
  const L = [];
  L.push('/* GENERATED by scripts/build-tokens.mjs from src/design/tokens.mjs — do not edit by hand.');
  L.push('   Change the source and run `npm run tokens`; tests/design-tokens.test.ts fails while this is stale. */');
  L.push('');
  L.push('@theme static {');
  L.push('  /* ---- primitives: OKLCH ramps ---- */');
  for (const [name, ramp] of Object.entries(T.RAMPS)) {
    for (const [step, lch] of Object.entries(ramp)) L.push(`  --color-${name}-${step}: ${oklchToHex(lch)}; /* ${css(lch)} */`);
  }
  L.push(`  --color-void: ${oklchToHex(T.voidBlack)};`);
  L.push('');
  L.push('  /* ---- semantics: light (the default) ---- */');
  for (const [role, r] of Object.entries(T.THEMES.light)) L.push(`  --color-${role}: ${ref(r)};`);
  L.push('');
  L.push('  /* ---- type ---- */');
  for (const [k, v] of Object.entries(T.FONTS)) L.push(`  --font-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.TYPE)) {
    L.push(`  --text-${k}: ${v.size};`);
    L.push(`  --text-${k}--line-height: ${v.leading};`);
    L.push(`  --text-${k}--letter-spacing: ${v.tracking};`);
  }
  L.push('');
  L.push('  /* ---- shape ---- */');
  for (const [k, v] of Object.entries(T.RADIUS)) L.push(`  --radius-${k}: ${v};`);
  L.push('');
  L.push('  /* ---- motion: curves ---- */');
  for (const [k, [v]] of Object.entries(T.EASE)) L.push(`  --ease-${k}: ${v};`);
  L.push('');
  L.push('  /* ---- the gap between a landing page’s sections (`mt-section`) ---- */');
  L.push(`  --spacing-section: ${T.SPACE.section};`);
  L.push('}');
  L.push('');
  L.push(':root {');
  for (const [k, v] of Object.entries(T.SPACE)) L.push(`  --space-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.MEASURE)) L.push(`  --measure-${k}: ${v};`);
  for (const [k, [v]] of Object.entries(T.DURATION)) L.push(`  --dur-${k}: ${v};`);
  L.push(`  --shadow-k: ${T.SHADOW_K.light};`);
  for (const [k, layers] of Object.entries(T.ELEVATION)) L.push(`  --elev-${k}: ${shadow(layers)};`);
  L.push(`  --edge-light: inset 0 1px 0 0 color-mix(in srgb, var(--color-paper-0) ${Math.round(T.EDGE_LIGHT.light * 100)}%, transparent);`);
  L.push(`  --grain-a: ${T.GRAIN.light};`);
  L.push(`  --grain-tile: ${T.GRAIN.tile};`);
  L.push(`  --wash-a: ${T.WASH.light};`);
  L.push(`  --wash-s: ${T.WASH.saturation};`);
  L.push(`  --wash-l: ${T.WASH.lightness};`);
  L.push('}');
  L.push('');
  L.push('/* Candlelit: the same ramps, read from the bottom. */');
  L.push('.dark {');
  for (const [role, r] of Object.entries(T.THEMES.dark)) L.push(`  --color-${role}: ${ref(r)};`);
  L.push(`  --shadow-k: ${T.SHADOW_K.dark};`);
  L.push(`  --edge-light: inset 0 1px 0 0 color-mix(in srgb, var(--color-paper-0) ${Math.round(T.EDGE_LIGHT.dark * 100)}%, transparent);`);
  L.push(`  --grain-a: ${T.GRAIN.dark};`);
  L.push(`  --wash-a: ${T.WASH.dark};`);
  L.push('}');
  L.push('');
  L.push('/* Paper does not take the screen palette (see PRINT in src/design/tokens.mjs). */');
  L.push('@media print {');
  L.push('  :root, .dark {');
  for (const [role, lch] of Object.entries(T.PRINT)) L.push(`    --color-${role}: ${oklchToHex(lch)}; /* ${css(lch)} */`);
  L.push('    --grain-a: 0;');
  L.push('  }');
  L.push('}');
  return L.join('\n') + '\n';
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const next = render();
  if (process.argv.includes('--check')) {
    let cur = '';
    try {
      cur = readFileSync(OUT, 'utf8');
    } catch {}
    if (cur !== next) {
      console.error('src/styles/tokens.css is stale — run `npm run tokens`');
      process.exit(1);
    }
    console.log('tokens.css is current');
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT.replace(process.cwd() + '/', '')} (${next.split('\n').length} lines)`);
  }
}
